# docker-compose.yml
version: '3.5'

services:
  taco-service:
    image: 'taco-service:latest'
    depends_on:
      - mongo
      - registry-service
      - keycloak
    build: ./taco-service
    container_name: taco

  ingredient-service:
    image: 'ingredient-service:latest'
    depends_on:
      - mongo
      - registry-service
      - keycloak
    build: ./ingredient-service
    container_name: ingredient

  order-service:
    image: 'order-service:latest'
    depends_on:
      - mongo
      - registry-service
      - keycloak
    build: ./order-service
    container_name: order

  registry-service:
    image: 'registry-service:latest'
    hostname: registry-service
    build: ./registry-service
    container_name: registry
    ports:
      - "8761:8761"

  api-gateway:
    image: 'api-gateway:latest'
    depends_on:
      - registry-service
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"

  # Database tier
  mongo:
    image: 'mongo:6.0.2-focal'
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db # ensures data persistence between restarting
    ports:
      - "27017:27017"
    command: mongod --logpath=/dev/null

  keycloak:
    image: 'jboss/keycloak:16.1.1'
    container_name: "keycloak"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: h2
    command: ["-Djboss.http.port=8085"]
    volumes:
      - ./data/keycloak/:/temp
    ports:
      - "8085:8085"

  taco-ui:
    image: 'taco-ui:latest'
    depends_on:
      - keycloak
    build: ./taco-ui
    container_name: taco-ui
    ports:
      - "4200:80"