global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  # Discover Eureka services to scrape.
  - job_name: 'eureka'
    metrics_path: '/actuator/prometheus'
    # Scrape Eureka itself to discover new services.
    eureka_sd_configs:
      - server: http://registry-service:8761/eureka
    oauth2:
      client_id: 'prometheus'
      client_secret: 'uZVVK26XiphhJpG5AacnbmY72C2axGTS'
      token_url: 'http://keycloak:8085/auth/realms/taco-realm/protocol/openid-connect/token'
      endpoint_params:
        grant_type: 'client_credentials'
