spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://keycloak:8085/auth/realms/taco-realm/protocol/openid-connect/token
            authorization-uri: http://keycloak:8085/auth/realms/taco-realm/protocol/openid-connect/auth
            user-info-uri: http://keycloak:8085/auth/realms/taco-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
        registration:
          keycloak:
            provider: keycloak
            client-id: gateway
            client-secret: PQdqbyiXhZU4efKMaBI0Pu8mDZenWChx
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
  cloud:
    gateway:
      default-filters:
        - TokenRelay=