spring:
  sleuth:
    reactor:
      # decorate_on_last might lead to medium performance degradation.
      instrumentation-type: decorate_on_last
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      routes:
        - id: taco-service
          uri: lb://TACO-SERVICE
          predicates:
            - Path=/tacos/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/tacos/v3/api-docs, /v3/api-docs

        - id: ingredient-service
          uri: lb://INGREDIENT-SERVICE
          predicates:
            - Path=/ingredients/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/ingredients/v3/api-docs, /v3/api-docs

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/orders/v3/api-docs, /v3/api-docs