spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: tacocloudtest

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://registry-service:8761/eureka/}