spring:
  data:
    rest:
      base-path: /api
    mongodb:
      host: localhost
      port: 27018
      database: tacocloudtest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/