spring:
  data:
    rest:
      base-path: /api
    mongodb:
      host: localhost
      port: 27018
      database: tacocloudtest
  rabbitmq:
    host: 127.0.0.1
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/