spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tacocloudtest
  rabbitmq:
    host: 127.0.0.1
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    ip-address: host.docker.internal